### ISSUE TITLE
Nested querying for requester username

### ISSUE THREAD

**Issue by Per-Plex** [CMPUT301W18T09/CDProjektBlue#10]

**Comment by AidanKosik** [comment]
Solved?

**Comment by Per-Plex** [comment]
Not solved but potentially unnecessary with the removal of the requester object.

**Comment by AidanKosik** [comment]
Can you think of any cases that this would still be an issue after the removal?

**Comment by Per-Plex** [comment]
Possibly with querying for a value in the bid list of a task.

**Comment by AidanKosik** [comment]
Okay, this can stay open until we verify if that is no longer an issue as well

**Comment by Per-Plex** [comment]
Commit has been pushed to data manager to fix this issue
