### ISSUE TITLE
Requester can't see bidders username

### ISSUE THREAD

**Issue by Z-Red** [CMPUT301W18T09/CDProjektBlue#18]
A requester must be able to see the username of individuals who have bidded on their tasks.

**Comment by Z-Red** [comment]
Please note, this is a preference and we intend to fix this for "wow" factor. This is not a user requirement. The intent is that a user can view a task providers reviews/ratings/details prior to accepting their bid. For example, someone may have a lower bid offer, but if they have poor reviews, maybe the requester does not want to choose them to do the task.

**Comment by AidanKosik** [comment]
There should be an option to view the user after clicking on a bid correct? Right now the bid card displays the username but there is no way of finding that provider. We need a way to do this to make viewing a rating possible. Do we want to make this an option where you accept or decline a bid? For example a button that says "view user" or we could just put the provider name in the dialog for accepting, so above the accept and decline buttons we would have the providers name and their ratings with a "link" to their reviews?

**Comment by AidanKosik** [comment]
Im closing this as it is technically completed, we can open one for its functionality when it becomes an issue.
