### ISSUE TITLE
Geo: Adding a new task returns you to the location selection map screen

### ISSUE THREAD

**Issue by Z-Red** [CMPUT301W18T09/CDProjektBlue#61]
After choosing a location for a task then proceeding to click "add", the program flow directs the user BACK to the previous page, which is, incidentally, the activity which lets you choose your location.

You should NOT be able to go back into the the location selection screen after adding the task

**Comment by Z-Red** [comment]
Moreover, when going back to this screen, you are able to pick yet another location, which proceeds to open up the create task activity once again.

**Comment by AidanKosik** [comment]
Fixed.
