### ISSUE TITLE
Reload Post-Crash Causes No Username To Exist

### ISSUE THREAD

**Issue by Z-Red** [CMPUT301W18T09/CDProjektBlue#64]
If the app crashes, then android asks the user to re-open the app, after it is loaded, no username will exist. This can be seen by opening the nav menu and seeing "" (empty string) for a username, thus resulting in a non-functioning app, as the newest change to the isNetworkAvailable function requires a username

**Comment by chaidar97** [comment]
This seems to not be an issue anymore, closing it for now.
