### ISSUE TITLE
Geo: Opening Maps via toggle switch does not request user permissions

### ISSUE THREAD

**Issue by Z-Red** [CMPUT301W18T09/CDProjektBlue#65]
Perhaps added a piece of code to the map activity like the one in AddEditTaskActivity...

`        // Initiate Location Client `
`        if (Build.VERSION.SDK_INT == Build.VERSION_CODES.M || permissionsGranted) {
            checkLocationPermission();
        }
`

**Comment by AidanKosik** [comment]
Did exactly that

**Comment by Z-Red** [comment]
Maybe important to note is that trying to open the maps from the toggle switch does result in a crash, but not after accepting the permissions from the AddEditTaskActivity dialog popup. Every time after that, no crash will occur. That is, this bug will only happen until the first time the user approves the permissions (which is not requested before opening maps via toggle switch).
